---
- name: Restart sshd if cron is running
  hosts: all
  become: yes
  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if cron is active
      ansible.builtin.shell: systemctl is-active cron
      register: cron_status
      ignore_errors: yes

    - name: Set SSH service name based on what's available
      set_fact:
        ssh_service: "{{ item }}"
      when: item in ansible_facts.services
      with_items:
        - sshd
        - ssh

    - name: Restart ssh service if cron is running
      ansible.builtin.service:
        name: "{{ ssh_service }}"
        state: restarted
      when:
        - cron_status.stdout == "active"
        - ssh_service is defined

